#!/usr/bin/env bash
# displays Username uid and home dir.

IFS ":"

while read -r username uid home; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
