#!/usr/bin/env bash
# uses while and if statements to print Best School x10 and Hi on a new line

counter=1

while [ $counter -le 10 ]

      if [ $counter -eq 9 ]
      then

	echo "Best School"
	echo "Hi"

      else

	echo "Best School"

      fi

      ((counter++))

done
