#!/usr/bin/env bash
# displays bad luck on #4, Good Luck on #8 and Best school on the others

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
	echo "Bad luck"
    elif [ $counter -eq 8]; then
	echo "Good luck"
    else
	echo "Best School"

    fi

    ((counter++))

done
