#!/usr/bin/env bash
# using a while loop to display hours and minutes

hours=0

while [ $hours -le 12 ]; do
    echo "Hour: $hours"

    minutes=1
        while [ $minutes -le 59 ]; do
	formatted_minutes=$(printf "%02d" $minutes)
        echo "$formatted_minutes"

	((minutes++))

    done

    ((hours++))

done
